apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-insight
  namespace: redis-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-insight
  template:
    metadata:
      labels:
        app: redis-insight
    spec:
      containers:
        - name: redis-insight
          image: redis/redis-stack-insight:latest
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: redis-insight
  namespace: redis-stack
spec:
  ports:
    - port: 8001
  selector:
    app: redis-insight
  type: ClusterIP
