apiVersion: v1
kind: Service
metadata:
  name: click-tex-tile-service
  namespace: click # Change the namespace name
spec:
  selector:
    app: click-tex-tile
  ports:
    - name: port-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 3050300000000000000000
  type: LoadBalancer
