apiVersion: v1
kind: Service
metadata:
  name: click-i-e-service
  namespace: click # Change the namespace name
spec:
  selector:
    app: click-i-e
  ports:
    - name: port-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30501
  type: LoadBalancer
