apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-deployment
  namespace: click # Change the namespace name
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
        - name: reactapp
          image: clickerp/react-app:26
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_CLIENT_NAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: CLIENT_NAME
            - name: REACT_APP_LINUX_NODE_ENV
              value: "production"
            - name: REACT_APP_LINUX_NODE_ENV
              value: "production"
