apiVersion: v1
kind: Service
metadata:
  name: reactapp-service
  namespace: click
  labels:
    app: reactapp
spec:
  selector:
    app: reactapp
  ports:
    - port: 80
      targetPort: 3000 # Replace with your app's container port if different
      nodePort: 30530
  type: LoadBalancer
