apiVersion: apps/v1
kind: Deployment
metadata:
  name: click-store-deployment
  namespace: click # Change the namespace name
spec:
  replicas: 3
  selector:
    matchLabels:
      app: click-store
  template:
    metadata:
      labels:
        app: click-store
    spec:
      containers:
        - name: click-store-container
          image: clickerp/store:560
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: my-secret
