apiVersion: apps/v1
kind: Deployment
metadata:
  name: click-produc-tion-deployment
  namespace: click # Change the namespace name
spec:
  replicas: 3
  selector:
    matchLabels:
      app: click-produc-tion
  template:
    metadata:
      labels:
        app: click-produc-tion
    spec:
      containers:
        - name: click-produc-tion-container
          image: clickerp/production:47
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: my-secret
