apiVersion: v1
kind: Service
metadata:
  name: click-produc-tion-service
  namespace: click # Change the namespace name
spec:
  selector:
    app: click-produc-tion
  ports:
    - name: port-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 50002
  type: LoadBalancer
