apiVersion: apps/v1
kind: Deployment
metadata:
  name: click-api-gateway-dep
  namespace: click # Change the namespace name
spec:
  replicas: 5
  selector:
    matchLabels:
      app: click-api-gateway-dep
  template:
    metadata:
      labels:
        app: click-api-gateway-dep
    spec:
      containers:
        - name: click-api-gateway-dep
          image: clickerp/apigateway:18
          ports:
            - containerPort: 80
