apiVersion: apps/v1
kind: Deployment
metadata:
  name: click-apigateway:41
  namespace: click # Change the namespace name
spec:
  replicas: 5
  selector:
    matchLabels:
      app: click-apigateway:41
  template:
    metadata:
      labels:
        app: click-apigateway:41
    spec:
      containers:
        - name: click-apigateway:41
          image: clickerp/apigateway:41
          ports:
            - containerPort: 80
