apiVersion: apps/v1
kind: Deployment
metadata:
  name: click-apigateway:39
  namespace: click # Change the namespace name
spec:
  replicas: 5
  selector:
    matchLabels:
      app: click-apigateway:39
  template:
    metadata:
      labels:
        app: click-apigateway:39
    spec:
      containers:
        - name: click-apigateway:39
          image: clickerp/apigateway:39
          ports:
            - containerPort: 80
