apiVersion: v1
kind: Service
metadata:
  name: click-apigateway-service
  namespace: click # Change the namespace name
spec:
  selector:
    app: click-apigateway
  ports:
    - name: port-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30500
  type: LoadBalancer
